### ISSUE TITLE
[unreal_pak] Add support for UE4_27

### ISSUE THREAD

**Issue by funlennysub** [AstroTechies/unrealmodding#31]
Currently `unreal_pak` doesn't seem work with Deep rock galactic which uses UE 4.27
![image](https://user-images.githubusercontent.com/26184007/201332717-27190c94-e3f7-4369-b9b0-949f6b9ae4b8.png)

**Comment by konsti219** [comment]
We currently don't support v11 but the crate was built with the intention to support it at some point. The reason it is not supported is the significantly different index format compared to v9. 

I am unsure how quickly one of us can get to implementing v11 but the relevant coffee is in index.rs and header.rs if you want to take a look at it.

**Comment by konsti219** [comment]
I just added support for reading v11 paks, but writing is not yet supported. But gonna close this for now becasue you mentioned extracting in your issue.
