### ISSUE TITLE
Lack of licensing information

### ISSUE THREAD

**Issue by atenfyr** [AstroTechies/unrealmodding#59]
None of the "crates" within this repository contain any sort of licensing information, which would appear to indicate that nobody can use them as part of any other project without obtaining explicit permission from each contributor or directly violating federal law in the United States. Each crate should include an appropriate license if you want these works to be used by others.

**Comment by konsti219** [comment]
We are currently in talks with all the people who have previously contributed to this codebase. Both @bananaturtlesandwich and @OmichronAgain have agreed to have the code dual licensed under MIT and Apache 2.0. We are just waiting on the approval of @trumank.
