### ISSUE TITLE
Failed to fill whole buffer on Village_Root and Invalid string size XXXXX at AZ_01 v2

### ISSUE THREAD

**Issue by Dastano** [AstroTechies/unrealmodding#73]
Lib issues? 

**Failed to Fill whole buffer**
Village_root
Village_root_TEMP
Village_MajiMarket_01_Root
AZ1_01_Gameplay_Narrative
AZ1_01_Gameplay
etc... (pretty much all Maps with Village)

**Invalid string Size xxxx**
FTUE_Root etc.
Community_Center_Main
AZ1_01_Root

**Comment by konsti219** [comment]
What version of `unreal_assst`?

**Comment by Dastano** [comment]
Latest commit, the Issue is pretty much for localcc, since I wrote with him in Discord. But you can check in as well. He said, it might be a Lib issue. 

Fixes are for Stove.
